### ISSUE TITLE
Releasing: check upfront the version doesn't exist already.

### ISSUE THREAD

**Issue by behaghel** [peter-mouland/web-caddy#79]
It could be generalised into dry-run before executing anything. I tried to release sky-tags v0.2.0 but the tag was already in use on `origin`. When the release fails in the middle, it's always a bit uncomfortable to know what should be undone and what to do next. The less chance to run in this case, the better.

**Comment by peter-mouland** [comment]
This issue has kind of been addressed in the continuous deployment branch #77.  Instead of showing an 'error' and bombing out it simply shows a 'warning' and continues.  This allows people to press the 'rebuild' button in circle without problems.

We could move the check higher up the stack but you could have other problems, I think local checking and remote checking may be overkill. Who do you trust? How much hand holding do we want or is it a case of clear error messages is good enough?

**Comment by peter-mouland** [comment]
patching the version number has been uncoupled from releasing.  The output logging of the tool has also been greatly increased.
This means that is you bump and release (`caddy bump && caddy release`), you can clearly see which part failed and re-run only the commands that need to be run again.  With the `git tag` only giving a warning rather than failing completely, even running the full `caddy release` wont do any harm.
